### PR TITLE
Add dependency to groovy-xml

### PR DESCRIPTION
**Pull request by martin-g**
Without it I face this error while building Apache Dubbo:

```
[ERROR] testAvailable  Time elapsed: 6.882 s  <<< ERROR!
    java.lang.NoClassDefFoundError: groovy/util/slurpersupport/GPathResult
    at org.apache.dubbo.registry.consul.ConsulRegistryTest.setUp(ConsulRegistryTest.java:55)
```

Updates:
- Groovy to 2.5.14
- JUnit4 to 4.13.2
- JUnit5 to 5.7.1

### CODE REVIEW

**Comment by szpak** [comment]
`groovy-xml` is not needed by embedded-consul. Unless I missed something important in your case, please just add it to your project.

See https://github.com/pszymczyk/embedded-consul/pull/102 for explanation.

**Comment by martin-g** [comment]
Thanks for explaining!
I still don't see how Dubbo depends on GPathResult but I guess you are right!

**Comment by martin-g** [comment]
I've figured it!
You use `compile 'org.codehaus.groovy.modules.http-builder:http-builder:0.7.1'` as a dependency and it uses the XML related classes: https://github.com/jgritman/httpbuilder/blob/72fb50a94cbd85f7cde17be0ea6b8e8375bc573e/src/main/java/groovyx/net/http/ParserRegistry.java#L26-L27
So, Embedded Consul does depend on groovy-xml!

**Comment by martin-g** [comment]
@szpak Do you agree with me that this PR should be reconsidered ?

**Comment by szpak** [comment]
I didn't expect that, but you seem to be right :-). `groovy-xml` was a part of `groovy.jar` in the past, so it is not a transitive dependency after we enforce groovy-2.5.

Btw, seeing:
```
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy</artifactId>
            <version>1.8.8</version>
```
in the httpbuilder's `pom.xml`, I'm glad it still works with Groovy 2.5...

Thanks for your PR. And thanks for Apache Wicket ;-).

**Review by szpak — APPROVED** [review]

**Comment by martin-g** [comment]
> in the httpbuilder's `pom.xml`, I'm glad it still works with Groovy 2.5...

If you feel adventurous you may want to replace it with https://http-builder-ng.github.io/http-builder-ng/ ;-)

**Comment by martin-g** [comment]
> Thanks for your PR. And thanks for Apache Wicket ;-).

Hehe :-)
Thank you too!

**Comment by szpak** [comment]
> If you feel adventurous you may want to replace it with https://http-builder-ng.github.io/http-builder-ng/ ;-)

[Unfortunately](https://github.com/http-builder-ng/http-builder-ng/):
> Dormant - The HttpBuilder-NG project is going dormant. Neither of us use the project any longer nor do we have the extra time to properly maintain it.

okhttp is some alternative, however rather 3.x as 4.x migrated to Kotlin, which introduces extra dependency. Nevertheless, it would probably need to be done by some external contribution :-).

**Pull request merged**
