### PR TITLE
support custom cdn for downloading consul

### PR DESCRIPTION
**Pull request by Panthro**
Adding the ability to setup a distinct place to look for the consul binary.

### CODE REVIEW

**Comment by Panthro** [comment]
Travis doesn't like me :-1: 

Please restart the job..

**Comment by pszymczyk** [comment]
Hi

I restart tests once but it's still failing. I think there is some real problem with tests.

**Comment by janisz** [comment]
Maybe you hit https://github.com/travis-ci/travis-ci/issues/7131#issuecomment-273239428

**Comment by Panthro** [comment]
Looks like it was it, using `dist: trusty` made it :+1:

**Comment by pszymczyk** [comment]
Gr8 thanks, I'll try to release today evening

**Pull request merged**
