### PR TITLE
Added ARM64 support to embedded-consul

### LINKED ISSUE #96: embedded-consul only works on amd64
The platform is amd64 without judgement.  Will it be updated to support other platform.
String url = "${cdn}${version}/consul_${version}_${os}_amd64.zip"

package com.pszymczyk.consul.infrastructure

class HttpBinaryRepository {

    public static final String CONSUL_BINARY_CDN = "CONSUL_BINARY_CDN"
    public static final String CONSUL_DEFAULT_CDN = "https://releases.hashicorp.com/consul/"
    private HttpsProtocolsSetter httpsProtocolsSetter

    HttpBinaryRepository() {
        this.httpsProtocolsSetter = new HttpsProtocolsSetter(new HttpsProtocolsSetter.SystemPropertiesStorage())
    }

    File getConsulBinaryArchive(String version, File file) {
        httpsProtocolsSetter.setRequiredTls(System.getProperty("java.version"), System.getProperty("https.protocols"))
        String os = OsResolver.resolve()
        String cdn = System.getenv(CONSUL_BINARY_CDN) != null ? System.getenv(CONSUL_BINARY_CDN)
                : System.getProperty(CONSUL_BINARY_CDN) != null ? System.getProperty(CONSUL_BINARY_CDN) : CONSUL_DEFAULT_CDN;
        String url = "${cdn}${version}/consul_${version}_${os}_amd64.zip"
        OutputStream outputStream = file.newOutputStream()
        outputStream << new URL(url).openStream()
        outputStream.close()
        file
    }
}

### PR DESCRIPTION
**Pull request by odidev**
Resolves #96 

Added code in HttpBinaryRepository.groovy file for setting url
according to the build architecture.

Signed-off-by: odidev <odidev@puresoftware.com>

### CODE REVIEW

**Comment by ruslansennov** [comment]
thanks

**Comment by odidev** [comment]
@ruslansennov 
Thanks for the merge. When are you planning to release in the maven repository?

**Comment by ruslansennov** [comment]
@pszymczyk take a look please

**Comment by pszymczyk** [comment]
Hi @odidev 
Many thanks for contribution, I will try to release new version soon.

**Comment by pszymczyk** [comment]
@odidev new library version with your change is in central now: https://repo1.maven.org/maven2/com/pszymczyk/consul/embedded-consul/2.2.0/

**Pull request merged**
