### PR TITLE
ACL tokens feature

### PR DESCRIPTION
**Pull request by pszymczyk**

### CODE REVIEW

**Comment by pszymczyk** [comment]
@aleksandrserbin

**Comment by pszymczyk** [comment]
@aleksandrserbin please let me know does it fits your needs.

**Comment by aleksandrserbin** [comment]
@pszymczyk, Yep, totally, thank you

**Comment by pszymczyk** [comment]
@aleksandrserbin great! It's quite big feature so I'd like to merge it after code review from @ruslansennov or @lazystone so feature will be in mvn central in coming days.

**Pull request merged**
